# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jul 13 14:33:28 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_finestraprincipale(object):
    def setupUi(self, finestraprincipale):
        finestraprincipale.setObjectName(_fromUtf8("finestraprincipale"))
        finestraprincipale.setEnabled(True)
        finestraprincipale.resize(719, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/gelatino_icon2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        finestraprincipale.setWindowIcon(icon)
        self.wid_centr = QtGui.QWidget(finestraprincipale)
        self.wid_centr.setObjectName(_fromUtf8("wid_centr"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.wid_centr)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_3 = QtGui.QFrame(self.wid_centr)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.widget_5 = QtGui.QWidget(self.frame_3)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget = QtGui.QWidget(self.widget_5)
        self.widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.usernameEdit = QtGui.QLineEdit(self.widget)
        self.usernameEdit.setObjectName(_fromUtf8("usernameEdit"))
        self.verticalLayout_7.addWidget(self.usernameEdit)
        self.passwordEdit = QtGui.QLineEdit(self.widget)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName(_fromUtf8("passwordEdit"))
        self.verticalLayout_7.addWidget(self.passwordEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.widget_5)
        self.widget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget_6 = QtGui.QWidget(self.widget_2)
        self.widget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.serverBox = QtGui.QComboBox(self.widget_6)
        self.serverBox.setMinimumSize(QtCore.QSize(355, 0))
        self.serverBox.setMaximumSize(QtCore.QSize(355, 16777215))
        self.serverBox.setEditable(False)
        self.serverBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.serverBox.setObjectName(_fromUtf8("serverBox"))
        self.horizontalLayout_2.addWidget(self.serverBox)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.widget_hostname = QtGui.QWidget(self.widget_2)
        self.widget_hostname.setEnabled(True)
        self.widget_hostname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_hostname.setObjectName(_fromUtf8("widget_hostname"))
        self.hostname_layout = QtGui.QHBoxLayout(self.widget_hostname)
        self.hostname_layout.setMargin(0)
        self.hostname_layout.setMargin(0)
        self.hostname_layout.setObjectName(_fromUtf8("hostname_layout"))
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.hostname_layout.addItem(spacerItem2)
        self.hostEdit = QtGui.QLineEdit(self.widget_hostname)
        self.hostEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.hostEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.hostEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hostEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhUrlCharactersOnly)
        self.hostEdit.setObjectName(_fromUtf8("hostEdit"))
        self.hostname_layout.addWidget(self.hostEdit)
        self.portaEdit = QtGui.QLineEdit(self.widget_hostname)
        self.portaEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.portaEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.portaEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.portaEdit.setObjectName(_fromUtf8("portaEdit"))
        self.hostname_layout.addWidget(self.portaEdit)
        self.verticalLayout_8.addWidget(self.widget_hostname)
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.buttonRegister = QtGui.QPushButton(self.widget_3)
        self.buttonRegister.setEnabled(False)
        self.buttonRegister.setObjectName(_fromUtf8("buttonRegister"))
        self.horizontalLayout_3.addWidget(self.buttonRegister)
        self.buttonConnect = QtGui.QPushButton(self.widget_3)
        self.buttonConnect.setEnabled(False)
        self.buttonConnect.setMaximumSize(QtCore.QSize(280, 16777215))
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.horizontalLayout_3.addWidget(self.buttonConnect)
        self.verticalLayout_8.addWidget(self.widget_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.frame_coll = QtGui.QFrame(self.frame_3)
        self.frame_coll.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_coll.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_coll.setObjectName(_fromUtf8("frame_coll"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frame_coll)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.scrollArea = QtGui.QScrollArea(self.frame_coll)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scroll_widget = QtGui.QWidget()
        self.scroll_widget.setGeometry(QtCore.QRect(0, 0, 677, 468))
        self.scroll_widget.setObjectName(_fromUtf8("scroll_widget"))
        self.scroll_layout_2 = QtGui.QGridLayout(self.scroll_widget)
        self.scroll_layout_2.setMargin(0)
        self.scroll_layout_2.setSpacing(0)
        self.scroll_layout_2.setObjectName(_fromUtf8("scroll_layout_2"))
        self.scrollArea.setWidget(self.scroll_widget)
        self.verticalLayout_6.addWidget(self.scrollArea)
        self.verticalLayout_3.addWidget(self.frame_coll)
        self.verticalLayout_4.addWidget(self.frame_3)
        finestraprincipale.setCentralWidget(self.wid_centr)
        self.menubar = QtGui.QMenuBar(finestraprincipale)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 719, 30))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFail = QtGui.QMenu(self.menubar)
        self.menuFail.setObjectName(_fromUtf8("menuFail"))
        self.menuAIUTO = QtGui.QMenu(self.menubar)
        self.menuAIUTO.setObjectName(_fromUtf8("menuAIUTO"))
        finestraprincipale.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(finestraprincipale)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        finestraprincipale.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(finestraprincipale)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        finestraprincipale.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionEsci = QtGui.QAction(finestraprincipale)
        self.actionEsci.setIcon(icon)
        self.actionEsci.setObjectName(_fromUtf8("actionEsci"))
        self.actionAbout_Thinkzone = QtGui.QAction(finestraprincipale)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/gelatino_icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionAbout_Thinkzone.setIcon(icon1)
        self.actionAbout_Thinkzone.setObjectName(_fromUtf8("actionAbout_Thinkzone"))
        self.menuFail.addAction(self.actionEsci)
        self.menuAIUTO.addAction(self.actionAbout_Thinkzone)
        self.menubar.addAction(self.menuFail.menuAction())
        self.menubar.addAction(self.menuAIUTO.menuAction())

        self.retranslateUi(finestraprincipale)
        self.serverBox.setCurrentIndex(-1)
        QtCore.QObject.connect(self.actionEsci, QtCore.SIGNAL(_fromUtf8("triggered()")), finestraprincipale.close)
        QtCore.QMetaObject.connectSlotsByName(finestraprincipale)

    def retranslateUi(self, finestraprincipale):
        finestraprincipale.setWindowTitle(QtGui.QApplication.translate("finestraprincipale", "Thinkzone", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameEdit.setPlaceholderText(QtGui.QApplication.translate("finestraprincipale", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordEdit.setPlaceholderText(QtGui.QApplication.translate("finestraprincipale", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.hostEdit.setPlaceholderText(QtGui.QApplication.translate("finestraprincipale", "hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.portaEdit.setPlaceholderText(QtGui.QApplication.translate("finestraprincipale", "4242", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRegister.setText(QtGui.QApplication.translate("finestraprincipale", "Registrati", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonConnect.setText(QtGui.QApplication.translate("finestraprincipale", "Log in", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFail.setTitle(QtGui.QApplication.translate("finestraprincipale", "fail", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAIUTO.setTitle(QtGui.QApplication.translate("finestraprincipale", "AIUTO!", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("finestraprincipale", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEsci.setText(QtGui.QApplication.translate("finestraprincipale", "esci", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout_Thinkzone.setText(QtGui.QApplication.translate("finestraprincipale", "about Thinkzone", None, QtGui.QApplication.UnicodeUTF8))

import immagini_rc
