# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created: Sun Jul 15 12:24:28 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(642, 132)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_5 = QtGui.QWidget(Dialog)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.widget = QtGui.QWidget(self.widget_5)
        self.widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.usernameEdit = QtGui.QLineEdit(self.widget)
        self.usernameEdit.setObjectName(_fromUtf8("usernameEdit"))
        self.verticalLayout_7.addWidget(self.usernameEdit)
        self.passwordEdit = QtGui.QLineEdit(self.widget)
        self.passwordEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordEdit.setObjectName(_fromUtf8("passwordEdit"))
        self.verticalLayout_7.addWidget(self.passwordEdit)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout_4.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.widget_5)
        self.widget_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.widget_6 = QtGui.QWidget(self.widget_2)
        self.widget_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_6.setObjectName(_fromUtf8("widget_6"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.serverBox = QtGui.QComboBox(self.widget_6)
        self.serverBox.setMinimumSize(QtCore.QSize(355, 0))
        self.serverBox.setMaximumSize(QtCore.QSize(355, 16777215))
        self.serverBox.setEditable(False)
        self.serverBox.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.serverBox.setObjectName(_fromUtf8("serverBox"))
        self.horizontalLayout_2.addWidget(self.serverBox)
        self.verticalLayout_8.addWidget(self.widget_6)
        self.widget_hostname = QtGui.QWidget(self.widget_2)
        self.widget_hostname.setEnabled(True)
        self.widget_hostname.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_hostname.setObjectName(_fromUtf8("widget_hostname"))
        self.hostname_layout = QtGui.QHBoxLayout(self.widget_hostname)
        self.hostname_layout.setMargin(0)
        self.hostname_layout.setMargin(0)
        self.hostname_layout.setObjectName(_fromUtf8("hostname_layout"))
        spacerItem2 = QtGui.QSpacerItem(0, 20, QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Minimum)
        self.hostname_layout.addItem(spacerItem2)
        self.hostEdit = QtGui.QLineEdit(self.widget_hostname)
        self.hostEdit.setMinimumSize(QtCore.QSize(300, 0))
        self.hostEdit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.hostEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.hostEdit.setInputMethodHints(QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhPreferLowercase|QtCore.Qt.ImhUrlCharactersOnly)
        self.hostEdit.setObjectName(_fromUtf8("hostEdit"))
        self.hostname_layout.addWidget(self.hostEdit)
        self.portaEdit = QtGui.QLineEdit(self.widget_hostname)
        self.portaEdit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.portaEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.portaEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhFormattedNumbersOnly)
        self.portaEdit.setObjectName(_fromUtf8("portaEdit"))
        self.hostname_layout.addWidget(self.portaEdit)
        self.verticalLayout_8.addWidget(self.widget_hostname)
        self.widget_3 = QtGui.QWidget(self.widget_2)
        self.widget_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.buttonRegister = QtGui.QPushButton(self.widget_3)
        self.buttonRegister.setEnabled(False)
        self.buttonRegister.setObjectName(_fromUtf8("buttonRegister"))
        self.horizontalLayout_3.addWidget(self.buttonRegister)
        self.buttonConnect = QtGui.QPushButton(self.widget_3)
        self.buttonConnect.setEnabled(False)
        self.buttonConnect.setMaximumSize(QtCore.QSize(280, 16777215))
        self.buttonConnect.setObjectName(_fromUtf8("buttonConnect"))
        self.horizontalLayout_3.addWidget(self.buttonConnect)
        self.verticalLayout_8.addWidget(self.widget_3)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.horizontalLayout_4.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.widget_5)

        self.retranslateUi(Dialog)
        self.serverBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.usernameEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Username", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.hostEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.portaEdit.setPlaceholderText(QtGui.QApplication.translate("Dialog", "4242", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRegister.setText(QtGui.QApplication.translate("Dialog", "Registrati", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonConnect.setText(QtGui.QApplication.translate("Dialog", "Log in", None, QtGui.QApplication.UnicodeUTF8))

